# Generated by Django 5.1.5 on 2025-02-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemonapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guests', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
