# Generated by Django 5.1.5 on 2025-02-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemonapi', '0003_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(unique=True),
        ),
    ]
