# Generated by Django 5.1.5 on 2025-02-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemonapi', '0004_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(),
        ),
    ]
