# Generated by Django 5.1.6 on 2025-02-08 16:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemonapi', '0009_alter_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
