# Generated by Django 5.1.6 on 2025-02-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemonapi', '0010_alter_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
